# Generated by Django 5.1.1 on 2024-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streaming',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
