# Generated by Django 5.1.1 on 2024-11-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0003_alter_streaming_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='video_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
