# Generated by Django 5.1.1 on 2024-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0005_streaming_recorded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='recorded_streams/'),
        ),
    ]
